services:
  database:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpass
      - POSTGRES_DB=pgdb

pipeline:
  build:
    image: python:3.7-slim
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://pguser:pgpass@database/pgdb
    commands:
      - cp -R . ~
      - cd ~
      - bash clean.sh
      - pip install pipenv
      - pipenv install --dev --system
      - export PYTHONPATH=.
      - pytest tests -v --cov=app --cov=tests
      - flake8 app
